### ISSUE TITLE
DeviceController feature request

### ISSUE THREAD

**Issue by GeorgeVentura** [CS350-01F17/Slicer#10]
public getters for variables:

- sdaConnected
- pauseRequest
- stopRequest
- jobRunning

so I can sync gui state with the device state

**Comment by wildtayne** [comment]
Added in 72931f9e95b444cf3ec5ad29c5f77e3f4f30beef:
- `serialConnected()` for sdaConnected
- `pauseRequested()` for pauseRequest
- `stopRequested()` for stopRequest
- `isJobRunning()` for jobRunning

**Comment by GeorgeVentura** [comment]
got everything to work except stopJob (tested with socat)

**Comment by wildtayne** [comment]
Does `stopJob()` not work or `stopRequested()` (or both)? `stopRequest` gets set to false as soon as `DeviceController` stops printing, so there is usually a pretty small window where `stopRequested()` will return true. `stopJob()` seems to work on my end, so I'll have to check out what is happening with it and the UI.

**Comment by wildtayne** [comment]
This appears to be because the GUI starts the cool down print job right after issuing `stopJob()`. Since the device controller is operating in its own thread, this causes `stopRequest` to be set to `true`, then `false`, before it has a chance to check it. A quick fix is to put a small delay in between stopping the job and starting a new one (@ZBoylan). This is not ideal, but it does work.
